site_name: Message Flux
repo_url: https://github.com/Avivsalem/MessageFlux

theme:
  name: readthedocs

nav:
  - Home: index.md
  - API References: api.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
            show_root_heading: true
            show_source: false
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition