# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Message Flux
repo_name: Avivsalem/MessageFlux
repo_url: https://github.com/Avivsalem/MessageFlux
edit_uri: edit/main/docs/

theme:
  name: material

nav:
  - Home: index.md
  - API References: api.md
  - Contributing To MessageFlux: contribute.md

plugins:
  - search
  # mkdocstrings is missing schema.json refers to the material schema
  - mkdocstrings: 
      handlers:
        python:
          options:
            show_root_heading: true
            show_source: false
            docstring_style: sphinx


markdown_extensions:
  - markdown.extensions.admonition
