site_name: Message Flux
theme:
  name: readthedocs

plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
            show_root_heading: true
            show_source: false
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition