# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Message Flux
repo_url: https://github.com/Avivsalem/MessageFlux

theme:
  name: material
  

nav:
  - Home: index.md
  - API References: api.md
  - Contributing To MessageFlux: contribute.md

plugins:
  - search
  # mkdocstrings missing schema.json integrated with material schema
  - mkdocstrings: 
      handlers:
        python:
          options:
            show_root_heading: true
            show_source: false


markdown_extensions:
  - markdown.extensions.admonition
