[build-system]
requires = [
    "setuptools",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "baseservice"
version = "0.0.1a"
requires-python = '>=3.7,<3.11'
readme = "README.md"
license = {file = "LICENSE"}
classifiers = [
    'Programming Language :: Python',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
]
dynamic = [
    "dependencies",
    "optional-dependencies"
]

[project.urls]
github-repo = "https://github.com/Avivsalem/BaseService"

[[project.authors]]
name = "Aviv Salem"
email = "avivsalem@gmail.com"

[[project.maintainers]]
name = "Aviv Salem"
email = "avivsalem@gmail.com"

[[project.maintainers]]
name = "Nir Schulman"
email = "narsssx@gmail.com"

[tool.setuptools]
packages = ["baseservice"]
platforms = [
    "win32",
    "linux"
]

[tool.setuptools.dynamic]
dependencies = {file = "requirements.txt"}
optional-dependencies = {dev = {file = "requirements-dev.txt"}, rabbitmq = { file = "requirements-rabbitmq.txt"}}

[tool.pytest.ini_options]
addopts = "--cov=./baseservice --cov-report term-missing --cov-report=html:./reports/coverage/html_results --cov-report xml:./reports/coverage/coverage-results.xml --junitxml=./reports/test-results.xml"
testpaths = [
    "tests"
]

[tool.tox]
legacy_tox_ini="""
[tox]
envlist = py{37,38,39,310}-{windows,linux}-pytest,py{39}-{windows,linux}-{flake8,mypy}
isolated_build = True

[gh-actions]
python =
    3.7: py37
    3.8: py38
    3.9: py39
    3.10: py310

[gh-actions:env]
PLATFORM =
    windows-latest: windows
    ubuntu-latest: linux

[testenv]
platform =
    linux: linux
    windows: win32
allowlist_externals =
    windows: cmd
    windows: powershell
    linux: mkdir
    linux: bash
commands_pre =
    linux: mkdir -p ./reports
    windows: cmd /c if not exist .\\reports mkdir .\\reports
    python -m pip install pip -U
    pip install .[dev]

[testenv:py{37,38,39,310}-{windows,linux}-pytest]
commands =
    linux: bash -c "pytest . | tee ./reports/test-console-results.txt"
    windows: powershell /c "pytest | Tee-Object .\\reports\\test-console-results.txt"
    windows: python -c "file = open('./reports/test-console-results.txt', 'rb');results=file.read();file.close();file = open('./reports/test-console-results.txt', 'wb');file.write(results.replace(b'\\r\\n', b'\\n'));file.close()"


[testenv:py{37,38,39,310}-{windows,linux}-mypy]
commands =
    mypy baseservice

[testenv:py{37,38,39,310}-{windows,linux}-flake8]
commands =
    flake8 baseservice tests
"""

[tool.mypy]
warn_unused_configs = true
check_untyped_defs = true
disallow_untyped_decorators = true
warn_unused_ignores = true
warn_unreachable = true
strict_equality = true
pretty = true
show_traceback = true
raise_exceptions = true
html_report = "./reports/mypy"
junit_xml = "./reports/mypy.xml"