# this workflow is for deploy

name: deploy prod

concurrency: production

on:
  # run this only after the tests workflow completed
  workflow_run:
    workflows: [ "tests" ]
    branches: [ main ]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # run only if tests succeeded
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set Up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Find latest version
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        with:
          semver_only: true

      - name: Build Project
        run: |
          pip install build
          python -m build

      - name: Twine Install and Check
        run: |
          pip install twine
          twine check dist/*

      - name: Twine Upload PyPi
        run: |
          twine upload -u __token__ -p ${{ secrets.MESSAGEFLUX_PYPI_TOKEN }} dist/*

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get-latest-tag.outputs.tag }}
          release_name: ${{ steps.get-latest-tag.outputs.tag }}
