name: deploy

concurrency: production

on:
  # run this only after the tests workflow completed
  workflow_run:
    workflows: [ "tests" ]
    branches: [ main ]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # run only if tests succeeded
    steps:
      # Checkout the latest code from the repo
      - name: Checkout repo
        uses: actions/checkout@v2

        # Setup Python
      - name: Set Up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Bump Version
        run: |
          pip install bump2version
          bump2version patch --allow-dirty

        # generate the requirements-all.txt file
      - name: Generate requirements-all.txt
        run: python make_all_extra_requirements.py

      - name: Build Project
        run: |
          pip install build
          python -m build

      - name: Twine Install and Check
        run: |
          pip install twine
          twine check dist/*

      - name: Twine Upload TestPyPi
        run: |
          twine upload -r testpypi -u __token__ -p ${{ secrets.MESSAGEFLUX_TESTPYPI_TOKEN }} dist/*

      - name: Twine Upload PyPi
        run: |
          twine upload -u __token__ -p ${{ secrets.MESSAGEFLUX_PYPI_TOKEN }} dist/*

      - name: Push Version Changes
        run: |
          git config --global user.name 'Aviv Salem'
          git config --global user.email 'Avivsalem@users.noreply.github.com'
          git push      
